### ISSUE TITLE
repository에 오타있어요.!!!ㅋ

### ISSUE THREAD

**Issue by khw7096** [redbean/Pruject_Euler#1]
Pruject -> Project
혹시나 해서 남겨요~! 저는 상관없지만 지원씨의 스마트함이 타인에게 혹시 낮게 비춰질지도 몰라서..ㅋㅋㅋ

**Comment by redbean** [comment]
으아악!!!! 이런 실수를 !! ㅠㅠㅠㅠ 감사합니다. 
몇일동안 ㅠㅠ이러고 있었다니 으악으악 ㅠㅠ 감사합니다 ㅠㅠ
